# Generated by Django 2.0.4 on 2018-04-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_host', models.CharField(max_length=15)),
                ('db_user', models.CharField(max_length=60)),
                ('db_pass', models.CharField(max_length=60)),
                ('db_name', models.CharField(max_length=60)),
                ('db_desc', models.CharField(max_length=200)),
                ('db_esta', models.IntegerField()),
            ],
        ),
    ]
